IGVF-1539 Audit_category in two places
IGVF-DACC/igvfd pull request #1064
Opened 2024-08-29 04:35 UTC by zhwshen

2024-08-29 17:44 UTC, ian-whaling commented on src/igvfd/audit/analysis_set.py
> +                    yield AuditFailure(audit_message_missing_samples.get('audit_category', ''), f'{detail} {audit_message_missing_samples.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:44 UTC, ian-whaling commented on src/igvfd/audit/analysis_set.py
> +                    yield AuditFailure(audit_message_unexpected_samples.get('audit_category', ''), f'{detail} {audit_message_unexpected_samples.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:44 UTC, ian-whaling commented on src/igvfd/audit/analysis_set.py
> +            yield AuditFailure(audit_message_missing_samples.get('audit_category', ''), f'{detail} {audit_message_missing_samples.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:44 UTC, ian-whaling commented on src/igvfd/audit/analysis_set.py
> +        yield AuditFailure(audit_message_missing_step_version.get('audit_category', ''), f'{detail} {audit_message_missing_step_version.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:45 UTC, ian-whaling commented on src/igvfd/audit/biosample.py
> +            yield AuditFailure(audit_message.get('audit_category', ''), f'{detail} {audit_message.get("audit_description", "")}', level='ERROR')
missing assigning the level

2024-08-29 17:45 UTC, ian-whaling commented on src/igvfd/audit/biosample.py
> +        yield AuditFailure(audit_message.get('audit_category', ''), f'{detail} {audit_message.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:46 UTC, ian-whaling commented on src/igvfd/audit/file_set.py
> +        yield AuditFailure('missing files', f'{detail} {audit_message.get("audit_description", "")}', level='WARNING')
missing assigning the level

2024-08-29 17:49 UTC, ian-whaling requested changes
missing assignment of the level in many places

2024-08-29 22:26 UTC, zhwshen commented on src/igvfd/audit/analysis_set.py
> +                    yield AuditFailure(audit_message_missing_samples.get('audit_category', ''), f'{detail} {audit_message_missing_samples.get("audit_description", "")}', level='WARNING')
Changed.

2024-08-29 22:26 UTC, zhwshen commented on src/igvfd/audit/analysis_set.py
> +                    yield AuditFailure(audit_message_unexpected_samples.get('audit_category', ''), f'{detail} {audit_message_unexpected_samples.get("audit_description", "")}', level='WARNING')
Changed.

2024-08-29 22:26 UTC, zhwshen commented on src/igvfd/audit/analysis_set.py
> +            yield AuditFailure(audit_message_missing_samples.get('audit_category', ''), f'{detail} {audit_message_missing_samples.get("audit_description", "")}', level='WARNING')
Changed.

2024-08-29 22:27 UTC, zhwshen commented on src/igvfd/audit/analysis_set.py
> +        yield AuditFailure(audit_message_missing_step_version.get('audit_category', ''), f'{detail} {audit_message_missing_step_version.get("audit_description", "")}', level='WARNING')
Changed.

2024-08-29 22:28 UTC, zhwshen commented on src/igvfd/audit/biosample.py
> +        yield AuditFailure(audit_message.get('audit_category', ''), f'{detail} {audit_message.get("audit_description", "")}', level='WARNING')
Addressed.

2024-08-29 22:29 UTC, zhwshen commented on src/igvfd/audit/biosample.py
> +            yield AuditFailure(audit_message.get('audit_category', ''), f'{detail} {audit_message.get("audit_description", "")}', level='ERROR')
Addressed.

2024-08-29 22:29 UTC, zhwshen commented on src/igvfd/audit/biosample.py
> +                yield AuditFailure(audit_message.get('audit_category', ''), f'{detail} {audit_message.get("audit_description", "")}', level='ERROR')
Addressed.

2024-08-29 22:30 UTC, zhwshen commented on src/igvfd/audit/file_set.py
> +        yield AuditFailure('missing files', f'{detail} {audit_message.get("audit_description", "")}', level='WARNING')
Addressed.

2024-08-30 20:41 UTC, ian-whaling commented on src/igvfd/audit/file.py
> +            yield AuditFailure('inconsistent document type', f'{detail} {audit_message.get("audit_description", "")}', level=audit_message.get('audit_level', ''))
missing audit category get

2024-08-30 20:44 UTC, ian-whaling commented on src/igvfd/tests/test_commands_make_audit_docstring_json.py
> +    # print(get_docstring_dict_from_function_name('igvfd.tests.fixtures.audit_docstring.function_with_docstring_improper_keys'))
remove print statement

2024-08-30 20:44 UTC, ian-whaling requested changes
minor comments

2024-08-30 21:39 UTC, ian-whaling approved these changes

2024-09-04 18:28 UTC, ian-whaling approved these changes

2024-09-04 18:30 UTC, merged