IGVF-243-sample-term-required-biosample
IGVF-DACC/igvfd pull request #136
Opened 2022-08-15 18:22 UTC by khzlin

2022-08-15 21:25 UTC, jenjou commented on src/igvfd/tests/fixtures/schemas/primary_cell.py
> +        'schema_version': '6'
I think the schema version should be 5 here.

2022-08-15 21:25 UTC, jenjou commented on src/igvfd/tests/fixtures/schemas/differentiated_cell.py
> +        'schema_version': '6'
I think the schema version should be 5 here.

2022-08-15 21:30 UTC, jenjou commented on src/igvfd/schemas/changelogs/biosample.md
> -
These blank lines can be kept as is (no need to remove)

2022-08-15 21:30 UTC, jenjou commented on src/igvfd/schemas/changelogs/whole_organism.md
> +* Add `biosample_term` to requirements.
We can add a blank line after this line

2022-08-15 22:33 UTC, jenjou requested changes
There's typos in 2 of the fixtures and some blank lines in the changelogs, otherwise looks ok.

2022-08-16 16:38 UTC, jenjou approved these changes

2022-08-21 16:21 UTC, KAndreeva commented on src/igvfd/schemas/changelogs/primary_cell.md
> +### Schema version 7
The primary_cell.json indicates version 6, but this changelog indicates version 7.

2022-08-22 16:37 UTC, gabdank requested changes
small comments on changelogs

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/biosample.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/cell_line.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/differentiated_cell.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/differentiated_tissue.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/primary_cell.md
> +### Schema version 7
Not sure the version should be 7, should not it be 6?
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/tissue.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 16:37 UTC, gabdank commented on src/igvfd/schemas/changelogs/whole_organism.md
> +* Add `biosample_term` to requirements.
I think better would be "Require 'biosample_term'."

2022-08-22 23:24 UTC, gabdank requested changes
cell_line.json says version 6, but cell_line changelog says 7. it should say 6.

2022-08-22 23:25 UTC, gabdank approved these changes

2022-08-23 23:31 UTC, merged