IGVF-268-ensembl-gene-id
IGVF-DACC/igvfd pull request #148
Opened 2022-08-31 19:47 UTC by khzlin

2022-09-01 16:58 UTC, gabdank requested changes

2022-09-01 16:58 UTC, gabdank commented on src/igvfd/schemas/changelogs/gene.md
> +* Change `geneID` to use ENCSEMBL ID instead of NCBI Entrez ID.
typo: ENCSEMBL -> ENSEMBL

2022-09-01 16:58 UTC, gabdank commented on src/igvfd/schemas/gene.json
> +                "pattern": "^((HGNC:\\d+)|(MGI:\\d+)|(MIM:\\d+)|(UniProtKB:[0-9A-Z]+)|(Vega:OTT[A-Z]+G\\d+)|(miRBase:MI\\d+)|(IMGT/GENE-DB:[0-9A-Za-z/\\(\\)\\-]+)|(RefSeq:[A-Z]{2}_[\\d.]+)|(GeneCards
please add to the regex the ENTREZ regex

2022-09-01 16:58 UTC, gabdank commented on src/igvfd/upgrade/gene.py
> +    value.pop('dbxrefs')
I am not sure there is a need to "pop" if you are assigning the value in the next line

2022-09-02 17:20 UTC, gabdank approved these changes

2022-09-06 17:06 UTC, khzlin commented
Closing ticket, Having trouble with making demos so I made a new branch at IGVF-268-ensembl-gene-id-b.

2022-09-07 22:55 UTC, closed without merging