IGVF-155-file
IGVF-DACC/igvfd pull request #152
Opened 2022-09-06 18:49 UTC by jenjou

2022-09-06 18:51 UTC, jenjou commented
@cricketsloan This ticket isn't "complete" yet, but I thought it would be helpful to have an initial review of what we have so far. We are missing a subschema that could be used for processed/non-raw data. Also, I need to remove the unused schema "data.json".

2022-09-07 00:26 UTC, gabdank requested changes

2022-09-07 00:26 UTC, gabdank commented on src/igvfd/schemas/file.json
> +            "description": "Identifiers from external resources that may have 1-to-1 or 1-to-many relationships with IGVF objects.",
I think it should be specific to "IGVF file objects" rather than general "IGVF objects"

2022-09-07 00:26 UTC, gabdank commented on src/igvfd/schemas/file.json
> +                "description": "Identifier from an external resource that may have 1-to-1 or 1-to-many relationships with IGVF objects.",
same comments as above "IGVF file objects"

2022-09-07 00:26 UTC, gabdank commented on src/igvfd/schemas/sequence_data.json
> +        "lab"
should not the required properties list be expanded in the sequence_data?

2022-09-07 00:26 UTC, gabdank commented on src/igvfd/schemas/sequence_data.json
> +        "content_type": {
I know that it may be very long, but perhaps we should add a comment with an explanation of what each of the enums is? with examples?

2022-09-07 00:26 UTC, gabdank commented on src/igvfd/types/file.py
> +    schema = load_schema('igvfd:schemas/sequence_data.json')
I think we need to add the md5 uniqueness function from ENCODE for the sequence_data

2022-09-19 17:44 UTC, gabdank requested changes
i think we should uniformly use either "File" or "file" otherwise it looks like in some places it is capitalized and in other it is not, while I don't think we mean there is difference between the object we are talking about

2022-11-14 17:56 UTC, gabdank requested changes

2022-11-14 17:56 UTC, gabdank commented on src/igvfd/schemas/imaging_data.json
> +                "tif"
I am wondering if, instead of TIF we would expect to get TAR-ball with multiple TIFFs?

2022-11-29 02:26 UTC, gabdank requested changes

2022-11-29 02:26 UTC, gabdank commented on src/igvfd/schemas/sequence_data.json
> +            "type": "string"
I think platform is required for FASTQ

2022-11-29 02:26 UTC, gabdank commented on src/igvfd/schemas/sequence_data.json
> +            "title": "Read Length",
I think read length, as well as reads count, should be calculated and fille din by the validator. So they should be required - after the uploading status changed to validated. not sure it is easy to do in dependencies

2022-12-02 17:46 UTC, gabdank approved these changes

2022-12-14 17:10 UTC, gabdank submitted a review, later dismissed

2022-12-19 19:57 UTC, gabdank approved these changes

2022-12-19 19:57 UTC, merged