IGVF-292-treatment-purpose-required
IGVF-DACC/igvfd pull request #153
Opened 2022-09-12 15:18 UTC by khzlin

2022-09-19 17:10 UTC, gabdank requested changes

2022-09-19 17:10 UTC, gabdank commented on src/igvfd/upgrade/treatment.py
> +@upgrade_step('treatment', '2', '3')
i think cleaner would be to turn any treatment not specifying purpose to be "perturbation" and add that info to "notes".

2022-09-19 21:08 UTC, khzlin commented on src/igvfd/schemas/changelogs/treatment.md
> +* Add `purpose` to requirements.
ok

2022-09-26 19:36 UTC, gabdank requested changes

2022-09-26 19:36 UTC, gabdank commented on src/igvfd/upgrade/treatment.py
> +        value['notes'] = 'This treatment did not have purpose specified previously, it was upgraded to have perturbation purpose.'
@khzlin you can not assume the notes field was empty, so need to concatenate rather than overwrite it

2022-10-06 13:41 UTC, gabdank requested changes

2022-10-06 13:41 UTC, gabdank commented on src/igvfd/upgrade/treatment.py
> +            notes + 'This treatment did not have purpose specified previously, it was upgraded to have perturbation purpose.').strip()
if 'notes' in value:
            value['notes'] = f'{value.get('notes')}. This treatment did not have..........'
else:
      value['notes'] = 'This treatment did not have..........'

2022-10-07 12:56 UTC, gabdank approved these changes

2022-10-20 17:58 UTC, merged