IGVF-6-inserts
IGVF-DACC/igvfd pull request #18
Opened 2022-03-29 04:31 UTC by ian-whaling

Added users, labs, awards from https://docs.google.com/spreadsheets/d/1OuGlwZkc5_GDGMsrwndhsNLi4rB672OsJ7bD1z-RTVI/edit#gid=1816188954

User emails are not actual emails, just their first name + email domain

2022-04-01 17:18 UTC, cricketsloan requested changes
Ian, thanks for putting this together, it will close out a bunch of related tickets as well.  I have a few questions in line.  What I did not validate was the content, specifically that all of the people and labs are connected properly.

2022-04-01 17:18 UTC, cricketsloan commented on src/igvfd/tests/data/inserts/user.json
> +            "community"
Shouldn't the default viewing group for the majority of these people be IGVF not community?

2022-04-01 23:36 UTC, ian-whaling commented on src/igvfd/tests/data/inserts/award.json
> +        "status": "current"
start dates aren't listed on the spreadsheet unless I should use a generic start_date (2021-09-01)? It is apparently in question if we even need start date. I added everything else

2022-04-05 15:54 UTC, cricketsloan commented on src/igvfd/tests/data/inserts/award.json
> +        "status": "current"
Is the idea to only have end date?  If we continue past the original awards we will need some sort of date to distinguish them.  But I am content leaving this off for now.

2022-04-06 22:21 UTC, merged