IGVF-328-Expand-HumanDonor-ethnicity
IGVF-DACC/igvfd pull request #212
Opened 2023-01-26 00:30 UTC by corismall

2023-01-26 01:36 UTC, gabdank requested changes
add human donor inserts utilizing your introduced ethnicities

2023-01-26 01:36 UTC, gabdank commented on src/igvfd/schemas/changelogs/human_donor.md
> +* Add `African Caribbean` to `ethnicity` enum.
please make it a single line listing all the additions to ethnicities

2023-01-26 01:36 UTC, gabdank commented on src/igvfd/schemas/changelogs/human_donor.md
> +* Add `African Caribbean` to `ethnicity` enum.
* Add `ethn1`,`etn2`, `etn3`,... to `ethnicities`

2023-01-26 01:36 UTC, gabdank commented on src/igvfd/schemas/changelogs/human_donor.md
> +* Add `African Caribbean` to `ethnicity` enum.
no need to say it is an enum

2023-01-26 22:10 UTC, corismall commented
accidentally clicked on merge branch instead of rebase

2023-01-31 22:14 UTC, gabdank approved these changes

2023-02-02 01:40 UTC, gabdank approved these changes

2023-02-02 01:57 UTC, merged