New properties of sample, cell_lines, and tissue schema.
IGVF-DACC/igvfd pull request #27
Opened 2022-04-15 14:44 UTC by KAndreeva

Initial implementation of new properties of sample, cell_lines, and tissue schema.

- nih_institutional_certification (added at the level of biosample use encodeD as a model) abstract class.  This is inherited by tissue and cell_lines classes.
- internal_tags (added in the mixins and then on the level of sample, use encodeD as a model but limit the tags).  This is inherited by tissue, cell_lines, and technical_sample classes.
- Added unit test for the new properties.

2022-04-15 17:53 UTC, cricketsloan reviewed
In Encode, I remembered internal tags being groupings like GTex and ENCORE.  The list of types of investigation is interesting.  How will it work?  Will we be tagging a biosample with what it was used to investigate?

2022-04-27 16:19 UTC, cricketsloan requested changes

2022-04-27 16:19 UTC, cricketsloan commented on src/igvfd/schemas/mixins.json
> +                    "Enhancers",
We have decided that we will restrict to ENCODE only at this point

2022-04-28 18:49 UTC, ian-whaling approved these changes

2022-04-28 22:17 UTC, ian-whaling approved these changes

2022-05-02 15:56 UTC, merged