IGVF-511-remove-yeast-wholeorganism
IGVF-DACC/igvfd pull request #284
Opened 2023-03-29 16:36 UTC by corismall

2023-03-29 17:31 UTC, gabdank requested changes
see comments

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/schemas/changelogs/biosample.md
> +* Remove `saccharomyces`.
I think this should be "Remove taxa saccharomyces."

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/schemas/changelogs/in_vitro_system.md
> +
I think this should be "Remove taxa saccharomyces."

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/schemas/changelogs/primary_cell.md
> +* Remove `saccharomyces`.
I think this should be "Remove taxa saccharomyces."

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/tests/test_schema_tissue.py
> -    res = testapp.patch_json(
I think you can just revert this test into 422?

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/tests/test_schema_whole_organism.py
> -    res = testapp.patch_json(
I think you can revert the test into 422?

2023-03-29 17:31 UTC, gabdank commented on src/igvfd/tests/test_upgrade_whole_organism.py
> +    assert value['schema_version'] == '10'
the notes should be checked as well?

2023-03-30 20:09 UTC, iyoungworth requested changes
The changelogs and tests look good, but one change in the upgrade code is requested. Also, the schema_version default value in each schema.json file (just the concrete class objects) needs to be bumped up by one

2023-03-30 20:09 UTC, iyoungworth commented on src/igvfd/upgrade/sample.py
> +        value['notes'] = 'Previous taxa: ' + value['taxa'] + ' is no longer valid.'
This line will overwrite any previous value for 'notes' in each object, so it's best to check for the current value and instead append your new comment. There are multiple ways to do this, you can take a look at some examples in /upgrade/treatment.py and /upgrade/donor.py to use as a starting point

2023-03-31 19:04 UTC, iyoungworth approved these changes
Code all looks good, pass. (Schema_version defaults are bumped by 2 to account for a previous merged upgrade ticket that missed this step)

2023-04-04 19:00 UTC, iyoungworth submitted a review, later dismissed

2023-04-06 17:42 UTC, iyoungworth approved these changes

2023-04-10 16:38 UTC, merged