IGVF-725-add-search-faq
IGVF-DACC/igvfd pull request #391
Opened 2023-06-07 00:58 UTC by keenangraham

2023-06-07 15:59 UTC, forresttanaka submitted a review, later dismissed
I think the FAQ format is good. The one content change I can think of, though I’ll have Idan decide if we need that or not, is the difference between `TOP_HITS_ITEM_TYPES` and `DEFAULT_ITEM_TYPES` so that someone maintaining this in the future knows when to make the the same or different.

2023-06-07 16:25 UTC, gabdank requested changes
can we add links?

2023-06-07 16:25 UTC, gabdank commented on src/igvfd/searches/README.md
> +A: Certain high-level document values, such as UUIDs and unique keys, are copied by default into the `_exact` field in Opensearch. You can look at the mapping for a type to see if a specific field is
can we add a path to the mappings example in the repo? i don't think we can assume everyone understands what "mapping" is

2023-06-07 16:25 UTC, gabdank commented on src/igvfd/searches/README.md
> +**Q: What are search configs?**
can we add a path to the search configs in the repo? i don't think we can assume everyone understands what search configs are.

2023-06-07 16:25 UTC, gabdank commented on src/igvfd/searches/README.md
> +**Q: What are search configs?**
similar to the link [`DEFAULT_ITEM_TYPES`](https://github.com/IGVF-DACC/igvfd/blob/b3714678fb6695a97a544eecb0afe403cdf149c9/src/igvfd/searches/defaults.py#L22-L60)

2023-06-07 16:25 UTC, gabdank commented on src/igvfd/searches/README.md
> +A: Certain high-level document values, such as UUIDs and unique keys, are copied by default into the `_exact` field in Opensearch. You can look at the mapping for a type to see if a specific field is
similar to the link [`DEFAULT_ITEM_TYPES`](https://github.com/IGVF-DACC/igvfd/blob/b3714678fb6695a97a544eecb0afe403cdf149c9/src/igvfd/searches/defaults.py#L22-L60)

2023-06-09 21:00 UTC, gabdank approved these changes

2023-06-09 21:02 UTC, merged