IGVF-727-add-delivery-to-measurement
IGVF-DACC/igvfd pull request #408
Opened 2023-06-15 19:25 UTC by KAndreeva

Added delivery property to the measurement set object.

2023-06-19 18:06 UTC, gabdank requested changes
test function name wrong

2023-06-19 18:06 UTC, gabdank commented on src/igvfd/tests/test_schema_measurement_set.py
> +def test_(testapp, measurement_set):
the name of the function is incomplete

2023-06-19 19:16 UTC, KAndreeva commented on src/igvfd/tests/test_schema_measurement_set.py
> +def test_(testapp, measurement_set):
Updated

2023-06-20 01:17 UTC, gabdank approved these changes

2023-06-20 17:19 UTC, merged