IGVF-660-audit-curated-set-taxa
IGVF-DACC/igvfd pull request #445
Opened 2023-07-14 23:03 UTC by jenjou

2023-07-15 00:52 UTC, ian-whaling requested changes
Does it make sense to implement control for a mixed taxa sample, which would have no taxa in sample(s) but donors of multiple taxa?

2023-07-17 23:28 UTC, jenjou commented
> Does it make sense to implement control for a mixed taxa sample, which would have no taxa in sample(s) but donors of multiple taxa?

This should be handled now, so that if it's mixed donor and the sample taxa is none (which implies that it has mixed taxa) the audit doesn't trigger.

2023-07-18 02:16 UTC, ian-whaling approved these changes

2023-07-18 19:45 UTC, ian-whaling approved these changes

2023-07-18 21:39 UTC, ian-whaling submitted a review, later dismissed

2023-07-18 23:56 UTC, ian-whaling approved these changes

2023-07-19 00:40 UTC, merged