IGVF-420-dashboards
IGVF-DACC/igvfd pull request #578
Opened 2023-09-20 23:51 UTC by ottojolanki

2023-09-21 18:45 UTC, keenangraham requested changes
Looks good, just some organizational stuff.

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +    def _define_log_driver_for_pyramid_container(self) -> None:
Can you put this right above where application container gets defined?

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +        self._define_log_driver_for_pyramid_container()
Group next to application container.

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +        self.dashboard = BackendDashboard(
I don't think we need to assign this to `self.dashboard`?

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +            'PyramidDashBoard',
'BackendDashboard'

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +    def _define_log_driver_for_pyramid_container(self) -> None:
`_define_log_driver_for_pyramid_container`
Can we call it `_define_log_driver_for_application_container` to be consistent?

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +    pyramid_log_driver: LogDriver
Can we call this `application_log_driver` to be consistent?

2023-09-21 18:45 UTC, keenangraham commented on cdk/infrastructure/constructs/dashboards/backend.py
> +            'BackendDashBoard'
'Dashboard'

2023-09-21 20:15 UTC, ottojolanki commented on cdk/infrastructure/constructs/backend.py
> +from aws_cdk.aws_cloudwatch import YAxisProps
thanks. forgot to remove after putting dashboard to separate module.

2023-09-22 19:38 UTC, keenangraham approved these changes
LGTM.

2023-09-25 17:52 UTC, keenangraham requested changes

2023-09-25 17:52 UTC, keenangraham commented on cdk/infrastructure/constructs/backend.py
> +            'BackendDashBoard',
`BackendDashboard`

2023-09-25 17:52 UTC, keenangraham commented on cdk/infrastructure/constructs/dashboards/backend.py
> +            'DashBoard'
`Dashboard`

2023-09-25 17:52 UTC, keenangraham commented on cdk/infrastructure/constructs/dashboards/backend.py
> +        )
I think we might need to define `dashboard_name` (https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_cloudwatch/Dashboard.html) here so we can tell which backend it's reporting on. Something like `dashboard_name = f'{self.props.config.common.project_name}-{self.props.config.branch}-backend'`.

2023-09-25 23:28 UTC, keenangraham approved these changes

2023-09-25 23:29 UTC, keenangraham approved these changes
LGTM.

2023-09-26 15:08 UTC, merged