IGVF-1140-reverse-link-on-parents
IGVF-DACC/igvfd pull request #626
Opened 2023-10-12 00:56 UTC by ian-whaling

2023-10-12 17:58 UTC, ian-whaling commented on src/igvfd/types/sample.py
> +        return paths_filtered_by_status(request, pooled_in)
This returns an array when I'd like it to just be a string since it will always just be a single link. Not sure how to accomplish this.

2023-11-01 17:58 UTC, ian-whaling commented on src/igvfd/types/sample.py
> +        return paths_filtered_by_status(request, pooled_in)
Never mind, an array is fine since a sample may be pooled in multiple other samples.

2023-11-07 01:23 UTC, gabdank requested changes

2023-11-07 01:23 UTC, gabdank commented on src/igvfd/types/sample.py
> +        'title': 'Parted Samples',
i think "Biosample Parts" would be better than "Parted Samples"

2023-11-07 01:23 UTC, gabdank commented on src/igvfd/types/sample.py
> +            'title': 'Parted Child Sample',
I think "Biosample Part" would be better than "Parted Child Sample"

2023-11-07 01:23 UTC, gabdank commented on src/igvfd/types/sample.py
> +            'title': 'Child Sample',
`Originated Sample` would be better than "Child sample"

2023-11-09 16:52 UTC, gabdank approved these changes

2023-11-13 23:04 UTC, merged