IGVF-1293-assembly-required
IGVF-DACC/igvfd pull request #702
Opened 2023-11-30 20:15 UTC by jenjou

2023-12-02 01:57 UTC, gabdank approved these changes

2023-12-05 20:57 UTC, gabdank requested changes
typo in test function

2023-12-05 20:57 UTC, gabdank commented on src/igvfd/tests/test_upgrade_alignment_file.py
> +def test_alignment_file_upgrade_2_3(upgrader, alignment_file_v3):
the name of the test should be 3->4

2023-12-05 21:27 UTC, jenjou commented on src/igvfd/tests/test_upgrade_alignment_file.py
> +def test_alignment_file_upgrade_2_3(upgrader, alignment_file_v3):
Fixed

2023-12-08 23:31 UTC, gabdank approved these changes

2023-12-13 18:34 UTC, gabdank approved these changes

2023-12-14 02:06 UTC, merged