IGVF-1268-originated-from-desc
IGVF-DACC/igvfd pull request #708
Opened 2023-12-04 20:37 UTC by ian-whaling

2023-12-05 20:10 UTC, khzlin requested changes
we don't have "dedifferentiation" classification

2023-12-05 20:31 UTC, khzlin approved these changes

2023-12-05 20:31 UTC, ian-whaling commented
> we don't have "dedifferentiation" classification

We do not have dedifferentiation classification but a sample can be originated from another through dedifferentiation. I don't think the classification is relevant here and the description for cell_fate_change_treatments references dedifferentation the same way.

2023-12-06 01:33 UTC, gabdank approved these changes

2023-12-06 01:34 UTC, merged