IGVF-1344-embed-fileset-construct
IGVF-DACC/igvfd pull request #727
Opened 2023-12-11 23:22 UTC by forresttanaka

I need this for [IGVF-1079](https://igvf.atlassian.net/browse/IGVF-1079) so that we can more efficiently retrieve the construct libraries associated with the sample objects associated with MeasurementSet or PredictionSet.

2023-12-11 23:24 UTC, forresttanaka commented
I don’t understand why I needed to add to the `FileSet` `samples.sample_terms` embedding to make this embedding work. I feel like `construct_library_set` has nothing to do with `sample_terms`, but without this addition, my embedding change has no effect.

2023-12-12 18:15 UTC, ian-whaling commented
> I don’t understand why I needed to add to the `FileSet` `samples.sample_terms` embedding to make this embedding work. I feel like `construct_library_set` has nothing to do with `sample_terms`, but without this addition, my embedding change has no effect.

The reason it's included in samples.sample_terms instead of just samples is that all of the properties specified in the "include" array are embedded from both objects as you go down the path samples->sample_terms. So instead of having two lines where samples has a list of properties to embed and samples.sample_terms has one as well we can just have one line. It also avoids traversing samples twice were we to have multiple lines.

2023-12-14 17:00 UTC, gabdank requested changes
i think this can go in, after mapping regeneration

2023-12-14 21:50 UTC, ian-whaling approved these changes

2023-12-18 19:48 UTC, merged