IGVF-1394-classifications-plural
IGVF-DACC/igvfd pull request #758
Opened 2024-01-26 19:00 UTC by jenjou

2024-01-29 19:25 UTC, gabdank requested changes
it looks like classifications in samples that are not in vitro system have not been updated in schemas, but in search configs they were? maybe the change in schemas was missed, or I am not sure I understand the logic.

2024-01-29 20:50 UTC, gabdank approved these changes

2024-01-30 11:45 UTC, khzlin commented on src/igvfd/schemas/in_vitro_system.json
> +                                    "contains": {
remove this line?

2024-01-31 18:32 UTC, gabdank submitted a review, later dismissed

2024-02-05 15:17 UTC, merged