IGVF-1016-standardize-assembly
IGVF-DACC/igvfd pull request #809
Opened 2024-03-01 00:55 UTC by ian-whaling

2024-03-01 17:58 UTC, gabdank requested changes
on many objects (like allignment file, gene) you remove hg19, mm9, mm10.. but the upgrade is not taking care of potential cases were these assemblies were used. I think you have to assume some objects used "old" assemblies and handle that gracefully (adding notes and changing to valid assembly) although we definitly have to try and clean up wrong assemblies by wrangling before this ticket gets in

2024-03-04 18:19 UTC, ian-whaling commented on src/igvfd/schemas/construct_library_set.json
> +            "default": "6"
The schema wasn't bumped from the previous upgrade of 4->5.

2024-03-04 18:19 UTC, ian-whaling commented on src/igvfd/schemas/prediction_set.json
> +            "default": "6"
The schema wasn't bumped from the previous upgrade of 4->5.

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/alignment_file.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/gene.md
> +* Move `assembly` on `locations` to mixins.
removed

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/genome_browser_annotation_file.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/human_genomic_variant.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/reference_file.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:22 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/signal_file.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:23 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/tabular_file.md
> +* Move `assembly` to mixins.
removed

2024-03-04 18:23 UTC, ian-whaling commented on src/igvfd/schemas/changelogs/variant.md
> +* Move `assembly` to mixins. (03/05/2024)
removed

2024-03-04 19:36 UTC, gabdank submitted a review, later dismissed

2024-03-05 17:57 UTC, merged