IGVF-1441-distinguish-part-originated
IGVF-DACC/igvfd pull request #855
Opened 2024-04-11 03:06 UTC by ian-whaling

2024-04-17 23:18 UTC, gabdank requested changes
duplicated entry in a list

2024-04-17 23:18 UTC, gabdank commented on src/igvfd/audit/sample.py
>                       'sorted_from', 'sorted_from_detail', 'revoke_detail', 'notes', 'submitter_comment',
sorted_from is duplicated

2024-04-17 23:58 UTC, ian-whaling commented on src/igvfd/audit/sample.py
>                       'sorted_from', 'sorted_from_detail', 'revoke_detail', 'notes', 'submitter_comment',
my mistake, fixed.

2024-04-18 19:56 UTC, gabdank approved these changes

2024-04-19 23:20 UTC, merged