IGVF-1662-add-protocols-sample-objects
IGVF-DACC/igvfd pull request #914
Opened 2024-05-22 04:01 UTC by khzlin

2024-05-22 18:01 UTC, gabdank requested changes
see pr comments

2024-05-22 18:01 UTC, gabdank commented on src/igvfd/schemas/changelogs/whole_organism.md
> +* Add `protocols`.
new change on top

2024-05-22 18:36 UTC, khzlin commented on src/igvfd/schemas/changelogs/primary_cell.md
> +* Add `protocols`.
done

2024-05-22 18:36 UTC, khzlin commented on src/igvfd/schemas/changelogs/multiplexed_sample.md
> +* Add `protocols`.
done

2024-05-22 18:36 UTC, khzlin commented on src/igvfd/schemas/changelogs/technical_sample.md
> +* Add `protocols`.
done

2024-05-22 18:36 UTC, khzlin commented on src/igvfd/schemas/changelogs/tissue.md
> +* Add `protocols`.
done

2024-05-24 16:54 UTC, gabdank submitted a review, later dismissed

2024-05-28 22:49 UTC, gabdank approved these changes

2024-05-28 23:24 UTC, merged