IGVF-1519-reverse-link
IGVF-DACC/igvfd pull request #965
Opened 2024-06-25 19:08 UTC by meenakshikagda

2024-06-25 19:10 UTC, ian-whaling commented on src/igvfd/types/biomarker.py
> +        'title': 'Biomarker for',
Use title case for property titles.

2024-06-25 19:10 UTC, ian-whaling commented on src/igvfd/types/biomarker.py
> +            'title': 'Biomarker for',
Use title case for property titles.

2024-06-25 19:11 UTC, ian-whaling commented on src/igvfd/types/biomarker.py
> +            'linkFrom': 'Sample.biomarkers',
biomarkers is on the level of Biosample so it should link from there instead.

2024-06-25 19:11 UTC, ian-whaling commented on src/igvfd/types/biomarker.py
> +    def input_to(self, request, biomarker_for):
property name should be biomarker_for

2024-06-25 19:12 UTC, ian-whaling commented on src/igvfd/types/file.py
> +        'title': 'Input to',
Use title case for property titles

2024-06-25 19:12 UTC, ian-whaling commented on src/igvfd/types/file.py
> +            'title': 'Input to',
Use title case for property titles

2024-06-25 19:17 UTC, ian-whaling commented on src/igvfd/types/modification.py
> +        'title': 'Samples modified',
Use title case for property titles

2024-06-25 19:17 UTC, ian-whaling commented on src/igvfd/types/modification.py
> +            'title': 'Samples modified',
Use title case for property titles

2024-06-25 19:17 UTC, ian-whaling commented on src/igvfd/types/modification.py
> +            'linkFrom': 'Sample.modifications',
modifications is on the level of Biosample so it should link from there instead.

2024-06-25 19:18 UTC, ian-whaling commented on src/igvfd/types/treatment.py
> +            'linkFrom': 'Sample.treatments',
treatments is on the level of Biosample so it should link from there instead.

2024-06-25 19:19 UTC, ian-whaling commented on src/igvfd/types/treatment.py
> +    def input_to(self, request, samples_treated):
property name should be samples_treated

2024-06-25 19:19 UTC, ian-whaling commented on src/igvfd/types/treatment.py
> +        'samples_treated': ('Sample', 'treatments')
treatments is on the level of Biosample so it should link from there instead.

2024-06-25 19:19 UTC, ian-whaling commented on src/igvfd/types/modification.py
> +        'samples_modified': ('Sample', 'modifications')
modifications is on the level of Biosample so it should link from there instead.

2024-06-25 19:19 UTC, ian-whaling commented on src/igvfd/types/biomarker.py
> +        'biomarker_for': ('Sample', 'biomarkers')
biomarkers is on the level of Biosample so it should link from there instead.

2024-06-25 19:20 UTC, ian-whaling requested changes
Some changes needed to function names, title case, and level of reverse link

2024-06-26 20:20 UTC, meenakshikagda commented
Created a new PR https://github.com/IGVF-DACC/igvfd/pull/969

2024-06-26 20:20 UTC, closed without merging