IGVF-1736-abstract-modification
IGVF-DACC/igvfd pull request #983
Opened 2024-07-05 17:35 UTC by jenjou

2024-07-09 20:22 UTC, keenangraham requested changes
Looks okay except I think the original Modification mapping needs to be manually deleted (https://github.com/IGVF-DACC/igvfd/blob/cee476760b3647a9cf2164917f92c352bead471b/src/igvfd/mappings/modification.json).

2024-07-09 21:17 UTC, jenjou commented
Deleted modification mapping. On a side note, we have mapping of sequence_data and human_genomic_variant that did not get deleted, that should probably be done (in a different ticket?)

2024-07-09 21:21 UTC, keenangraham commented
Yes, please delete here if they no longer exist.

2024-07-09 22:35 UTC, keenangraham submitted a review, later dismissed

2024-07-15 19:13 UTC, keenangraham approved these changes

2024-07-16 18:56 UTC, merged